[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = 'context_filetype.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/neosnippet.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_add = 'source $XDG_CONFIG_HOME/nvim/rc/plugins/deoplete.vim'

# use coc.nvim
# [[plugins]]
# repo = 'neoclide/coc.nvim'
# build = 'yarn install --frozen-lockfile'
# hook_source = 'source $XDG_CONFIG_HOME/nvim/after/coc.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
on_i = 1
hook_source = '''
  call denite#custom#map('insert', '<c-n>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<c-p>', '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'

if = 'has("nvim") && has("python3")'
[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_event = 'InsertEnter'
build = './install.sh'
on_ft = ['ruby', 'go', 'python', 'typescript', 'javascript']
